name: bricks

on:
  workflow_dispatch:

jobs:
  deploy:
    name: 'Deploy bundle to DEV'
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.TF_ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.TF_ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.TF_ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TF_ARM_TENANT_ID }}
      DATABRICKS_HOST: ${{ secrets.ADB_ACCOUNT_HOST }}
      DATACONTRACT_DATABRICKS_HTTP_PATH: c
      DATACONTRACT_DATABRICKS_TOKEN: c

    steps:
      # Faz o checkout do repositório principal
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Import directory to Databricks workspace
        run: |
          python3 -m pip install datacontract-cli[all]

      - name: Import directory to Databricks workspace
        run: |
          ls -la

      - name: Import directory to Databricks workspace
        run: |
          cd datamaster/jarvis_prep/
          datacontract test datacontract.yaml
