name: 99. Action BONUS Project Quality

# Action utiliza do cluster usuario principal + token para validar dado gerado.

on:
  workflow_dispatch:

jobs:
  deploy:
    name: 'Quality Contract Check'
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.TF_ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.TF_ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.TF_ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TF_ARM_TENANT_ID }}
      DATABRICKS_HOST: ${{ secrets.ADB_ACCOUNT_HOST }}
      DATABRICKS_HTTP_PATH: ${{ secrets.ADB_COMPUTE_HTTP_PATH }}
      DATABRICKS_TOKEN: ${{ secrets.ADB_USER_TOKEN }}

    steps:
      # Faz o checkout do repositório principal
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: download datacontract-cli
        run: |
          python3 -m pip install datacontract-cli[all]

      - name: run quality test datacontract
        run: |
          cd datamaster/jarvis_prep/
          datacontract test datacontract.yaml
