name: Setup Lakehouse Data Master

# Este arquivo de workflow do GitHub Actions é utilizado para configurar e implantar
# um ambiente de Lakehouse no Azure utilizando Terraform. Ele é composto por quatro jobs principais:
# 1. build: Faz o checkout de um repositório privado e faz o upload de artefatos necessários.
# 2. setup-lakehouse: Configura o ambiente de Lakehouse utilizando Terraform.
# 3. setup-unity-catalog: Configura o Unity Catalog no Azure Databricks utilizando Terraform.
# 4. setup-adb-compute: Configura os recursos de computação do Azure Databricks utilizando Terraform.
#
# O workflow é acionado manualmente através da aba Actions no GitHub.
# Ele utiliza runners do Ubuntu para executar os jobs e faz uso de variáveis de ambiente
# e segredos armazenados no GitHub para autenticação e configuração.

# Define quando o workflow será executado
on:
  # Permite executar este workflow manualmente a partir da aba Actions
  workflow_dispatch:

# Define os jobs que serão executados no workflow
jobs:
  # Primeiro job: build
  build:
    name: Strife Build
    # Define o tipo de runner que o job será executado
    runs-on: ubuntu-latest

    # Define os passos que serão executados no job
    steps:
      # Faz o checkout de outro repositório privado
      - name: Check out my other private repo
        uses: actions/checkout@v4
        with:
          repository: lealdouglas/strife

      # Faz o upload dos artefatos necessários
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: lakehouse
          path: ${{ github.workspace }}/azsetup/lakehouse
      - name: Upload Artifact Unity
        uses: actions/upload-artifact@v1
        with:
          name: lakehouseuc
          path: ${{ github.workspace }}/azsetup/lakehouse-adbuc
      - name: Upload Artifact Compute
        uses: actions/upload-artifact@v1
        with:
          name: lakehousecp
          path: ${{ github.workspace }}/azsetup/lakehouse-adbcompute

  # Job para configurar o ambiente de Lakehouse
  setup-lakehouse:
    name: Strife Setup Lakehouse
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ github.workspace }}/azsetup/lakehouse

    env:
      ARM_CLIENT_ID: ${{ secrets.TF_ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.TF_ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.TF_ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TF_ARM_TENANT_ID }}

    environment:
      name: dev

    needs: build
    steps:
      # Baixa o artefato do Terraform
      - name: Download Terraform
        uses: actions/download-artifact@v2
        with:
          name: lakehouse
          path: ${{ github.workspace }}/azsetup/lakehouse

      # Configura e inicializa o Terraform
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Terraform Init
        run: terraform init

      # Valida a configuração do Terraform
      - name: Terraform Validate
        run: terraform validate -no-color

      # Gera e aplica o plano de execução do Terraform
      - name: Terraform Plan
        run: terraform plan -no-color -var "envv=${{vars.ENVV}}"
        continue-on-error: true
      - name: Terraform Apply
        run: terraform apply -auto-approve -var "envv=${{vars.ENVV}}"

  # Job para configurar o Unity Catalog
  setup-unity-catalog:
    name: Strife Setup Unity Catalog
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ github.workspace }}/azsetup/lakehouse-adbuc

    env:
      ARM_CLIENT_ID: ${{ secrets.TF_ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.TF_ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.TF_ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TF_ARM_TENANT_ID }}

    environment:
      name: dev

    needs: setup-lakehouse
    steps:
      # Baixa o artefato do Terraform
      - name: Download Terraform
        uses: actions/download-artifact@v2
        with:
          name: lakehouseuc
          path: ${{ github.workspace }}/azsetup/lakehouse-adbuc

      # Configura e inicializa o Terraform
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Terraform Init
        run: terraform init

      # Valida a configuração do Terraform
      - name: Terraform Validate
        run: terraform validate -no-color

      # Gera e aplica o plano de execução do Terraform
      - name: Terraform Plan
        run: terraform plan -no-color -var "account_id=${{ secrets.ADB_ACCOUNT_ID}}" -var "azure_client_id=${{ secrets.TF_ARM_CLIENT_ID}}" -var "azure_client_secret=${{ secrets.TF_ARM_CLIENT_SECRET}}" -var "azure_tenant_id=${{ secrets.TF_ARM_TENANT_ID}}" -var "envv=${{vars.ENVV}}"
        continue-on-error: true
      - name: Terraform Apply Target Module
        run: terraform apply -target='module.metastore_and_users' -auto-approve -var "account_id=${{ secrets.ADB_ACCOUNT_ID}}" -var "azure_client_id=${{ secrets.TF_ARM_CLIENT_ID}}" -var "azure_client_secret=${{ secrets.TF_ARM_CLIENT_SECRET}}" -var "azure_tenant_id=${{ secrets.TF_ARM_TENANT_ID}}" -var "envv=${{vars.ENVV}}"
      - name: Terraform Apply
        run: terraform apply -auto-approve -var "account_id=${{ secrets.ADB_ACCOUNT_ID}}" -var "azure_client_id=${{ secrets.TF_ARM_CLIENT_ID}}" -var "azure_client_secret=${{ secrets.TF_ARM_CLIENT_SECRET}}" -var "azure_tenant_id=${{ secrets.TF_ARM_TENANT_ID}}" -var "envv=${{vars.ENVV}}"

  # Job para configurar os recursos de computação do ADB
  setup-adb-compute:
    name: Strife Setup ADB Compute
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ github.workspace }}/azsetup/lakehouse-adbcompute

    env:
      ARM_CLIENT_ID: ${{ secrets.TF_ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.TF_ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.TF_ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TF_ARM_TENANT_ID }}

    environment:
      name: dev

    needs: setup-unity-catalog
    steps:
      # Baixa o artefato do Terraform
      - name: Download Terraform
        uses: actions/download-artifact@v2
        with:
          name: lakehousecp
          path: ${{ github.workspace }}/azsetup/lakehouse-adbcompute

      # Configura e inicializa o Terraform
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Terraform Init
        run: terraform init

      # Valida a configuração do Terraform
      - name: Terraform Validate
        run: terraform validate -no-color

      # Gera e aplica o plano de execução do Terraform
      - name: Terraform Plan
        run: terraform plan -no-color -var "account_id=${{ secrets.ADB_ACCOUNT_ID}}" -var "azure_client_id=${{ secrets.TF_ARM_CLIENT_ID}}" -var "azure_client_secret=${{ secrets.TF_ARM_CLIENT_SECRET}}" -var "azure_tenant_id=${{ secrets.TF_ARM_TENANT_ID}}" -var "envv=${{vars.ENVV}}"
        continue-on-error: true
      - name: Terraform Apply
        run: terraform apply -auto-approve -var "account_id=${{ secrets.ADB_ACCOUNT_ID}}" -var "azure_client_id=${{ secrets.TF_ARM_CLIENT_ID}}" -var "azure_client_secret=${{ secrets.TF_ARM_CLIENT_SECRET}}" -var "azure_tenant_id=${{ secrets.TF_ARM_TENANT_ID}}" -var "envv=${{vars.ENVV}}"
